/ros2_laser_scan_merger:
  ros__parameters:
    lidar_topics:
      - "/mid70/front_scan/points"
      - "/mid70/right_scan/points"
      - "/mid70/left_scan/points"
    enabled_lidars:
      - true
      - true
      - true
    target_frame: "mara_top_deck"
    publish_merged_pointcloud: true
    publish_merged_scan: true
    sync: true
    voxel_size: 0.1

    cropbox_x: 0.91
    cropbox_y: 0.82
    cropbox_z: 3.0

    # Per-lidar filtering settings (relative to the target_frame)
    min_ranges: [0.2, 0.8, 0.8] 
    max_ranges: [15.0, 15.0, 15.0] 
    min_angles: [-0.61435, -2.35, 0.1] 
    max_angles: [0.61435, -0.1, 2.35] 

    enable_filter_scan: false
    enable_filter_cloud: true
    
    pointCloudTopic_out: /mid70/merged_points # merged point cloud from all lasers
    laserScanTopic_out: /mid70/merged_scans # merged laserscan from all lasers

    use_sim_time: true

/merged_pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.02
    angle_max: 1.5
    angle_min: -1.5
    inf_epsilon: 1.0
    max_height: 1.5
    min_height: -0.5 # base_link/top_deck placed at z = 0.608 m
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          # durability: volatile
          # history: keep_last
          reliability: best_effort
    queue_size: 10
    range_max: 20.0
    range_min: 0.1
    scan_time: 0.1
    #target_frame: mara_top_deck
    transform_tolerance: 0.01
    use_inf: false #  If disabled, report infinite range (no obstacle) as range_max + 1. Otherwise report infinite range as +inf.
    use_sim_time: true
