/ros2_laser_scan_merger:
  ros__parameters:
    flip1: false
    flip2: false
    inverse1: false
    inverse2: false
    laser1Alpha: 0.0
    laser1AngleMax: 70.4
    laser1AngleMin: -70.4
    laser1B: 0
    laser1G: 0
    laser1R: 255
    laser1XOff: 1.0
    laser1YOff: 0.0
    laser1ZOff: 0.34
    laser2Alpha: 180.0
    laser2AngleMax: 70.4
    laser2AngleMin: -70.4
    laser2B: 255
    laser2G: 0
    laser2R: 0
    laser2XOff: -1.0
    laser2YOff: 0.0
    laser2ZOff: 0.34
    pointCloudTopic: /mid70/merged_points # merged point cloud from both lasers
    pointCloudFrameId: mara_top_deck
    qos_overrides./parameter_events.publisher.depth: 1000
    # qos_overrides./parameter_events.publisher.durability: volatile
    # qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: best_effort
    scanTopic1: /mid70/front_scan/scan # LaserScan from front laser
    scanTopic2: /mid70/rear_scan/scan # Laserscan from rear laser
    show1: true
    show2: true
    use_sim_time: true

/merged_pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.02
    # angle_max: 1.5708
    # angle_min: -1.5708
    angle_max: 3.14
    angle_min: -3.14
    inf_epsilon: 1.0
    max_height: 10.0
    min_height: 0.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          # durability: volatile
          # history: keep_last
          reliability: best_effort
    queue_size: 10
    range_max: 20.0
    range_min: 0.1
    scan_time: 0.1
    target_frame: mara_top_deck
    transform_tolerance: 0.01
    use_inf: true
    use_sim_time: true
