/front_pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.02
    angle_max: 0.61
    angle_min: -0.61
    inf_epsilon: 1.0
    max_height: 3.0
    min_height: 0.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          # durability: volatile
          # history: keep_last
          reliability: best_effort
    queue_size: 10
    range_max: 20.0
    range_min: 0.1
    scan_time: 0.3333
    transform_tolerance: 0.01
    use_inf: true
    use_sim_time: True

/rear_pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.02
    angle_max: 0.61
    angle_min: -0.61
    inf_epsilon: 1.0
    max_height: 3.0
    min_height: 0.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          # durability: volatile
          # history: keep_last
          reliability: best_effort
    queue_size: 16
    range_max: 20.0
    range_min: 0.1
    transform_tolerance: 0.01
    use_inf: true
    use_sim_time: True